add AudioContextOptions to AudioContext
orottier/web-audio-api-rs pull request #36
Opened 2021-10-26 09:24 UTC by Jerboas86

The user can now specify:
- the number of output channels  
- the sample rate
- the output latency
when building its `AudioContext`.

If the intented options are not met by the audio hardware capabilities, the `AudioContext` is built with `default_config` options, and a warning is printed to the user.

If the user options are missing, the `AudioContext` is built with `primary_config` options. If the `primary_config` options are not met by the audio harware capabilities, the `AudioContext` is built with `default_config` options, and a warning is printed to the user.

This PR modify `DestinationNode`:
- Adds `max_channels_count` method
- Assert `ChannelCountConstraints` on `DestinationNode`

This PR adds merger.rs example to demonstrate new capabilities.

Clippy passes on `context.rs` and `io.rs`

related to #35
related to #28

2021-11-02 16:40 UTC, orottier requested changes
Interesting work, thanks!

2021-11-02 16:40 UTC, orottier commented on src/io.rs
> +            match opts.latency_hint {
Can you move this block into a helper function, makes it a bit more readable and then we can re-use if for the InputBuilder

2021-11-02 16:40 UTC, orottier commented on src/io.rs
> +pub fn build_input() -> (Stream, StreamConfig, Receiver<AudioBuffer>) {
You should port the latency hint to the input builder too (can be done in another PR if it's too much work). They should be symmetrical in the end

2021-11-02 16:40 UTC, orottier commented on src/context.rs
> +            .send_timeout(message, Duration::from_millis(10))
Why opt for timeout? If the requested latency `> 10millis`, this will fail for no good reason

2021-11-02 16:40 UTC, orottier commented on src/context.rs
>          // make buffer_size always a multiple of BUFFER_SIZE, so we can still render piecewise with
I think actually this is no longer needed, now we can handle varying buffer lengths.
We can remove this code in another PR

2021-11-02 16:40 UTC, orottier commented on src/context.rs
> +    pub const fn length(&self) -> usize {
no const please

2021-11-04 10:37 UTC, Jerboas86 reviewed
> You should port the latency hint to the input builder too (can be done in another PR if it's too much work)

I didn't port the refactoring to the input stream. leave it as "good first issue" or for another PR, provide that you agree on the refactoring :)

2021-11-04 10:37 UTC, Jerboas86 commented on src/io.rs
> +    /// # Warning
As mentioned here the correctness of the API is not enforce by the type system. I could make it more strict but at the cost of more complexity. What do you think ?

2021-11-10 07:13 UTC, merged

2021-11-10 16:24 UTC, Jerboas86 commented
> I didn't port the refactoring to the input stream. i leave it as "good first issue" or for another PR
 
is it Ok with you, if i open a good first issue about this topic?

2021-11-10 16:31 UTC, orottier commented
Go ahead!