Feature/params
orottier/web-audio-api-rs pull request #60
Opened 2021-11-30 10:05 UTC by b-ma

Hey, here is the `SetTargetAtTime` plus a couple of fixes and renaming

2021-11-30 18:24 UTC, orottier commented
This looks very good! I like the new naming, and the comments you have added. I will have a more thorough look soon

2021-12-01 14:19 UTC, orottier requested changes
Some small nitpicks. After that, ready to merge!

2021-12-01 14:19 UTC, orottier commented on src/param.rs
> +    fn unsafe_peek(&self) -> Option<&AudioParamEvent> {
`unsafe` is a bit misleading here. Maybe `unsorted_peek`?

2021-12-01 14:19 UTC, orottier commented on src/param.rs
> +                                let exponant =
spelling: exponent

2021-12-01 14:19 UTC, orottier commented on src/param.rs
> +                                let exponant = -1. * ((end_time - start_time) / time_constant);
spelling: exponent

2021-12-01 14:19 UTC, orottier commented on src/param.rs
> +    // the last rendered block, which means `intrisic_value must be calculated
missing backtick after intrisic_value

2021-12-01 15:37 UTC, merged

2021-12-01 15:45 UTC, b-ma commented
cool! thank for reviewing